//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquaTherm.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClientMeterReading
    {
        public int КлиентID { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Адрес { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
        public string НомерСчетчика { get; set; }
        public Nullable<double> ПоследниеПоказания { get; set; }
        public Nullable<System.DateTime> ДатаПоказаний { get; set; }
    }
}
