//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquaTherm.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Платежи
    {
        public int ID { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> idClient { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
    }
}
